
import numpy as np

GRID_LENGTH = 1
SCREEN_WIDTH = 480 - GRID_LENGTH
SCREEN_HEIGHT = 480 - GRID_LENGTH

NUM_COLS = SCREEN_WIDTH // GRID_LENGTH
NUM_ROWS = SCREEN_HEIGHT // GRID_LENGTH

GRAV_CONST = 1
WALL_COLLISION = True
SIM_SPEED = 1

# each successive collisions transparency
OUTPUT_CONTRAST = 0.2
MIN_GRID_LENGTH = 4
TRANSPARENCY = 0.5
UPDATE_PIXEL_INTERVAL = 2