import numpy as np

# each successive collisions transparency
COLLISION_BRIGHTNESS_FACTOR = np.array([0.5, 0.25, 0.125, 0.06, 0.03, 0.015, 0.008])
NUM_BRIGHTNESS_FACTOR = len(COLLISION_BRIGHTNESS_FACTOR)

SCREEN_WIDTH = 480
SCREEN_HEIGHT = 480

GRID_LENGTH = 4
NUM_COLS = SCREEN_WIDTH // GRID_LENGTH
NUM_ROWS = SCREEN_HEIGHT // GRID_LENGTH

GRAV_CONST = 1
WALL_COLLISION = True
SIM_SPEED = GRID_LENGTH

TRACK_INDEX = 0
PIXEL_CONTRAST = 0.01

PI = 3.1416