import numpy as np

SCREEN_WIDTH = 480
SCREEN_HEIGHT = 480

GRID_LENGTH = 1
NUM_COLS = SCREEN_WIDTH // GRID_LENGTH
NUM_ROWS = SCREEN_HEIGHT // GRID_LENGTH

TRACK_INDEX = 0

GRAV_CONST = 1
WALL_COLLISION = True
SIM_SPEED = 1

# each successive collisions transparency
COLLISION_BRIGHTNESS = np.array([1] + [1 / 2 ** (x + 1) for x in range(0)])
NUM_COLLISION_DRAWS = len(COLLISION_BRIGHTNESS)
OUTPUT_CONTRAST = 0.1

